### ISSUE TITLE
OverflowError: Python int too large to convert to C ssize_t

### ISSUE THREAD

**Issue by madeyemoody3** [shanefontaine/uniswap-python#22]
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
dai = "0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359"
test = uniswap_wrapper.get_token_token_input_price( weth , dai, 1*10**18)

returns bug
OverflowError: Python int too large to convert to C ssize_t

**Comment by redw1nejr** [comment]
Same here.

**Comment by zhaohongrong** [comment]
i got the same error

**Comment by redw1nejr** [comment]
I think this is related to eth-abi/web3 interaction 

 #https://github.com/ethereum/eth-abi/issues/142
#https://github.com/ethereum/web3.py/issues/1634

**Comment by redw1nejr** [comment]
decode_abi in contract.py of Web3.py expects a tuple. decode_single would work correctly but would need to know where to slice the hex payload for each data type.

**Comment by CryptoGnome** [comment]
Anyone find a solution to this?

**Comment by ErikBjare** [comment]
The error is cryptic, but there's nothing wrong with uniswap-python itself here. As you can see from my comment in https://github.com/ethereum/web3.py/issues/1634#issuecomment-663606227, I also stumbled into this error when developing V2 support and was similarly confused (for quite a while, I might add).

The problem is that you're calling `get_token_to_token_input_price`, which tries to check the price for the route `token1 -> (w)eth -> token2`. Since you're calling it with WETH, it fails when trying to check the price for `WETH -> WETH`, I'm not sure why that (and possibly other invalid inputs) leads to the cryptic error, but that's outside the scope of my knowledge of Web3.py internals.

Both these examples work fine:

```
# Does what you want
dai = "0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359"
test = uniswap.get_eth_token_input_price(dai, 1*10**18)
```

```
# Using another token than WETH
usdc = Web3.toChecksumAddress("0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48")
dai = "0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359"
test = uniswap.get_eth_token_input_price(usdc, dai, 1*10**18)
```

**Comment by CryptoGnome** [comment]
Thanks for the response @ErikBjare

**Comment by ErikBjare** [comment]
I figured we can probably do better, so I made a PR looking to prevent this from happening by automatically dispatching to eth_token or token_eth if one of the token addresses are WETH: (just a sec)

**Comment by CryptoGnome** [comment]
> I figured we can probably do better, so I made a PR looking to prevent this from happening by automatically dispatching to eth_token or token_eth if one of the token addresses are WETH: #31

Great Idea! This should solve this from popping up again
