### ISSUE TITLE
Is it possible to increase Gas Price  ? 

### ISSUE THREAD

**Issue by odannis** [shanefontaine/uniswap-python#70]
Hi,

I wondered if it could be possible to increase the gas price or select one value? 
I already look at the code. I saw that I could set the max quantity of gas used. But I found nothing on the Gas Price.

Thank you for your help and your work !!

**Comment by ErikBjare** [comment]
Duplicate, see the other issues.

**Comment by odannis** [comment]
Sorry for the duplicate !! Thank you

**Comment by legendagain** [comment]
Sorry for reviving a question, maybe just a suggestion could we allow the user to specify an optional parameter when instantiating `uniswap`? I am thinking this parameter can be a function that returns an integer (gas price in wei), so the user can specify the way he wishes to specify prices prior to each transaction (could be via Web3 strategy, ETH gas station, a fixed constant or otherwise).

If specified, this function will be triggered in `uniswap._get_tx_params()` to specify the `gasPrice` in the txn parameters. If it is not specified, then nothing will happen (i.e. web3 sets using its own strategy).

Let me know your thoughts!

**Comment by ErikBjare** [comment]
Seems unnecessary when you can already use Web3 gas strategies to achieve
the same thing.
